#!/usr/bin/env python3
"""Rebuild shapes/shapes.js from the individual chord JSON files.

Run from the repo root after adding or editing any shapes/*.json:

    python3 tools/build_shapes_bundle.py

The bundle exists so the tool also works when index.html is opened straight
from disk (file:// pages cannot fetch() sibling JSON files).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "shapes")

idx = json.load(open(os.path.join(D, "index.json")))
chords = {}
for fn in sorted(os.listdir(D)):
    if fn.endswith(".json") and fn != "index.json":
        chords[fn] = json.load(open(os.path.join(D, fn)))

bundle = {"index": idx, "chords": chords}
out = os.path.join(D, "shapes.js")
with open(out, "w") as f:
    f.write("// generated by tools/build_shapes_bundle.py — do not edit by hand\n")
    f.write("window.OSO_SHAPES=" + json.dumps(bundle, separators=(",", ":")) + ";\n")
print(f"wrote {out}: {len(chords)} chords, {len(idx)} symbol aliases")
